package com.mytiki.sdk.capture.receipt.capacitor.receipt

class Product(
    val productNumber: StringType?,
    val productDescription: StringType?,
    val quantity: FloatType?,
    val unitPrice: FloatType?,
    val unitOfMeasure: StringType?,
    val totalPrice: FloatType?,
    val fullPrice: Float,
    val line: Int,
    val productName: String?,
    val brand: String?,
    val category: String?,
    val size: String?,
    val rewardsGroup: String?,
    val competitorRewardsGroup: String?,
    val upc: String?,
    val imageUrl: String?,
    val shippingStatus: String?,
    val additionalLines: List<AdditionalLine>?,
    val priceAfterCoupons: FloatType?,
    val isVoided: Boolean,
    val probability: Double,
    val sensitive: Boolean,
    val possibleProducts: List<Product>?,
    val subProducts: List<Product>?,
    val added: Boolean,
    val blinkReceiptBrand: String?,
    val blinkReceiptCategory: String?,
    val extendedFields: MutableMap<String, String>? = null,
    val fuelType: String?,
    val modified: Boolean,
    val upcModified: Boolean,
    val imageUrlModified: Boolean,
    val productNameModified: Boolean,
    val brandModified: Boolean,
    val descriptionPrefix: StringType?,
    val descriptionPostfix: StringType?,
    val skuPrefix: StringType?,
    val skuPostfix: StringType?,
    val attributes: MutableList<Map<String, String>>?,
    val sector: String?,
    val department: String?,
    val majorCategory: String?,
    val subCategory: String?,
    val itemType: String?,
)