package com.mytiki.sdk.capture.receipt.capacitor.receipt

import java.util.Date

data class Receipt(
    val receiptDate: StringType?,
    val receiptTime: StringType?,
    val retailerId: Int,
    val products: MutableList<Product>?,
    val coupons: List<Coupon>?,
    val total: FloatType?,
    val tip: FloatType?,
    val subtotal: FloatType?,
    val taxes: FloatType?,
    val storeNumber: StringType?,
    val merchantName: StringType?,
    val storeAddress: StringType?,
    val storeCity: StringType?,
    val blinkReceiptId: String,
    val storeState: StringType?,
    val storeZip: StringType?,
    val storeCountry: StringType?,
    val storePhone: StringType?,
    val cashierId: StringType?,
    val transactionId: StringType?,
    val registerId: StringType?,
    val paymentMethods: List<PaymentMethod>?,
    val taxId: StringType?,
    val mallName: StringType?,
    val last4Digits: StringType?,
    val ocrConfidence: Float,
    val merchantSource: String?,
    val foundTopEdge: Boolean,
    val foundBottomEdge: Boolean,
    val eReceiptOrderNumber: String?,
    val eReceiptOrderStatus: String?,
    val eReceiptRawHtml: String?,
    val eReceiptShippingAddress: String?,
    val shipments: List<Shipment>?,
    val longTransactionId: StringType?,
    val subtotalMatches: Boolean,
    val eReceiptEmailProvider: String?,
    val eReceiptEmailId: String?,
    val eReceiptAuthenticated: Boolean,
    val isInstacartShopper: Boolean,
    val eReceipt: Boolean,
    val eReceiptComponentEmails: List<Receipt>?,
    val duplicate: Boolean,
    val fraudulent: Boolean,
    val receiptDateTime: Date? = null,
    val duplicateBlinkReceiptIds: List<String>?,
    val merchantMatchGuess: StringType?,
    val productsPendingLookup: Int,
    val qualifiedPromotions: List<Promotion>?,
    val unqualifiedPromotions: List<Promotion>?,
    val extendedFields: MutableMap<String, String>? = null,
    val eReceiptAdditionalFees: MutableMap<String, String>? = null,
    val purchaseType: StringType?,
    val loyaltyForBanner: Boolean,
    val channel: StringType?,
    val submissionDate: Date? = null,
    val eReceiptFulfilledBy: String?,
    val eReceiptShippingStatus: String?,
    val eReceiptPOSSystem: String?,
    val eReceiptSubMerchant: String?,
    val qualifiedSurveys: List<Survey>?,
    val barcode: String?,
    val eReceiptMerchantEmail: String?,
    val eReceiptEmailSubject: String?,
    val eReceiptShippingCosts: Float,
    val currencyCode: String?,
    val clientMerchantName: String?,
    val loyaltyProgram: Boolean,
    val merchantSources: List<Int?>?,
    val paymentTerminalId: StringType?,
    val paymentTransactionId: StringType?,
    val combinedRawText: StringType?,
)